### ISSUE TITLE
Anchor error: insufficient fees

### ISSUE THREAD

**Issue by DoesntPlayAnymore** [terraswapper/anchor_borrow_earn_bot#3]
Hello, when doing the automatic earn deposit after automatic borrow I am getting this error:
"Anchor error: do_trx
13 : insufficient fees; got: "1000000uusd", required: "190000uaud,190000ucad,140000uchf,980000ucny,900000udkk,125000ueur,110000ugbp,1170000uhkd,2180000000uidr,10880000uinr,16370000ujpy,169770000ukrw,11330uluna,428571000umnt,1250000unok,7600000uphp,104938usdr,1250000usek,200000usgd,4620000uthb,1568659uusd" = "190000uaud,190000ucad,140000uchf,980000ucny,900000udkk,125000ueur,110000ugbp,1170000uhkd,2180000000uidr,10880000uinr,16370000ujpy,169770000ukrw,11330uluna,428571000umnt,1250000unok,7600000uphp,104938usdr,1250000usek,200000usgd,4620000uthb,150000uusd"(gas) +"1418659uusd"(stability): insufficient fee"

However, there is well over 1000 ust on the account. The deposit size is 50000 ust. The collateral is bEth at 43% tvl (before the auto borrow). There is no bLuna on the account. Is this an error on my end? The bot works fine on an another account that uses bLuna. (I disabled the showing of Liquidation price on bLuna, but I do not believe this is relevant for the problem.)

**Comment by verustech** [comment]
Are you using the latest version?  The developer updated (I think last week) and it's working for us.

**Comment by DoesntPlayAnymore** [comment]
No. I will try that and report back.

**Comment by terraswapper** [comment]
As @verustech said, it should be fixed since version 2.0.2.

**Comment by terraswapper** [comment]
Is it good for you @DoesntPlayAnymore  ?
